name: my_test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_centos:
    name: build_centos
    runs-on: [self-hosted, centos]
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos7
        compiler:
          - gcc-9.2
    env:
      CCACHE_DIR: /tmp/ccache/nebula/${{ matrix.os }}-${{ matrix.compiler }}
      CCACHE_MAXSIZE: 8G
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
      volumes:
        - /tmp/ccache/nebula/${{ matrix.os }}-${{ matrix.compiler }}:/tmp/ccache/nebula/${{ matrix.os }}-${{ matrix.compiler }}
      options: --cap-add=SYS_PTRACE
    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "find . -mindepth 1 -delete"
      - uses: actions/checkout@v2
      - name: Prepare environment
        id: prepare
        run: |
          [ -d build/ ] && rm -rf build/* || mkdir -p build
          make init -C tests
      - name: CMake
        id: cmake
        run: |
          cmake \
              -DCMAKE_CXX_COMPILER=$TOOLSET_CLANG_DIR/bin/g++ \
              -DCMAKE_C_COMPILER=$TOOLSET_CLANG_DIR/bin/gcc \
              -DCMAKE_BUILD_TYPE=Release \
              -DENABLE_TESTING=on \
              -B build
          echo "::set-output name=j::10"
          echo "::set-output name=t::10"

      - name: Make
        run: |
          ccache -z
          cmake --build build/ -j ${{ steps.cmake.outputs.t }} --target nebula-metad nebula-storaged nebula-graphd
          cmake --build build/ -j ${{ steps.cmake.outputs.t }}
          ccache -s
      - name: CTest
        env:
          ASAN_OPTIONS: fast_unwind_on_malloc=1
        run: ctest -j $(($(nproc)/2+1)) --timeout 400 --output-on-failure
        working-directory: build/
        timeout-minutes: 20
      - name: Setup cluster
        run: |
          make CONTAINERIZED=true up

        working-directory: tests/
        timeout-minutes: 2
      - name: Pytest
        run: |
          make RM_DIR=false DEBUG=false J=${{ steps.cmake.outputs.j }} test
        working-directory: tests/
        timeout-minutes: 15
      - name: TCK
        run: |
          make RM_DIR=false DEBUG=false J=${{ steps.cmake.outputs.j }} tck
        working-directory: tests/
        timeout-minutes: 60
      - name: Down cluster
        run: |
          make RM_DIR=false down
        working-directory: tests/
        timeout-minutes: 2
      - name: Sanitizer
        if: ${{ always() }}
        run: |
          exit $(grep -P "SUMMARY: AddressSanitizer: \d+ byte\(s\) leaked in \d+ allocation\(s\)\." build/server_*/logs/*stderr.log | wc -l)
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: ${{ matrix.os }}-${{ matrix.compiler }}-nebula-test-logs
          path: ./build/server_*/logs/
