name: release_test

on:
  release:
    types:
      - published
concurrency:
  group: release
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  docker_build:
    name: docker-build
    runs-on: self-hosted
    # strategy:
    #   fail-fast: false

    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "find . -mindepth 1 -delete"
      - uses: actions/checkout@v2
      - name: Check License Header
        uses: apache/skywalking-eyes@main
      - uses: ./.github/actions/tagname-action
        id: tagname
      - id: docker
        run: |
          majorver=$(git tag -l --sort=v:refname | tail -n1 | cut -f1 -d'.')
          tag=""
          if [[ $majorver == v${{ steps.tagname.outputs.majorver }} ]]; then
            tag="latest"
          fi
          echo "::set-output name=tag::$tag"
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: reg.vesoft-inc.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          tags: |
            reg.vesoft-inc.com/vesoft/nebula-graphd:${{ steps.tagname.outputs.tag }}
            reg.vesoft-inc.com/vesoft/nebula-graphd:${{ steps.tagname.outputs.majorver }}
            reg.vesoft-inc.com/vesoft/nebula-graphd:${{ steps.docker.outputs.tag }}
          target: graphd
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          tags: |
            reg.vesoft-inc.com/vesoft/nebula-metad:${{ steps.tagname.outputs.tag }}
            reg.vesoft-inc.com/vesoft/nebula-metad:${{ steps.tagname.outputs.majorver }}
            reg.vesoft-inc.com/vesoft/nebula-metad:${{ steps.docker.outputs.tag }}
          target: metad
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          tags: |
            reg.vesoft-inc.com/vesoft/nebula-storaged:${{ steps.tagname.outputs.tag }}
            reg.vesoft-inc.com/vesoft/nebula-storaged:${{ steps.tagname.outputs.majorver }}
            reg.vesoft-inc.com/vesoft/nebula-storaged:${{ steps.docker.outputs.tag }}
          target: storaged
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          tags: |
            reg.vesoft-inc.com/vesoft/nebula-tools:${{ steps.tagname.outputs.tag }}
            reg.vesoft-inc.com/vesoft/nebula-tools:${{ steps.tagname.outputs.majorver }}
            reg.vesoft-inc.com/vesoft/nebula-tools:${{ steps.docker.outputs.tag }}
          target: tools
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}
